version: '3.9'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://postgres:%40gr1ff1n%23@localhost/zimra_api_db
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zimra_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
