"""change_device_id_to_string_in_fiscal_day

Revision ID: aa335d6de24e
Revises: edd7f639fd7b
Create Date: 2025-08-01 14:46:01.323689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa335d6de24e'
down_revision = 'edd7f639fd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign key constraint
    with op.batch_alter_table('fiscal_day', schema=None) as batch_op:
        batch_op.drop_constraint('fiscal_day_device_id_fkey', type_='foreignkey')
    
    # Then alter the column type
    with op.batch_alter_table('fiscal_day', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiscal_day', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fiscal_day_device_id_fkey'), 'device_info', ['device_id'], ['id'])
        batch_op.alter_column('device_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
