"""add device global number table

Revision ID: add_device_global_number_table
Revises: add_device_configuration_table
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'device_global_number_001'
down_revision = 'device_config_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_global_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('current_global_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device_info.device_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_global_number')
    # ### end Alembic commands ### 