"""add_device_configuration_table

Revision ID: device_config_001
Revises: manual_invoice_001
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'device_config_001'
down_revision = 'manual_invoice_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create device_configuration table
    op.create_table('device_configuration',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.String(length=50), nullable=False),
        
        # Tax Payer Information
        sa.Column('tax_payer_name', sa.String(length=255), nullable=True),
        sa.Column('tax_payer_tin', sa.String(length=50), nullable=True),
        sa.Column('vat_number', sa.String(length=50), nullable=True),
        
        # Device Information
        sa.Column('device_serial_no', sa.String(length=100), nullable=True),
        sa.Column('device_branch_name', sa.String(length=255), nullable=True),
        sa.Column('device_operating_mode', sa.String(length=50), nullable=True),
        sa.Column('tax_payer_day_max_hrs', sa.Integer(), nullable=True),
        
        # QR URL
        sa.Column('qr_url', sa.String(length=255), nullable=True),
        
        # Operation ID
        sa.Column('operation_id', sa.String(length=100), nullable=True),
        
        # Address Information
        sa.Column('device_branch_address_province', sa.String(length=100), nullable=True),
        sa.Column('device_branch_address_city', sa.String(length=100), nullable=True),
        sa.Column('device_branch_address_street', sa.String(length=255), nullable=True),
        sa.Column('device_branch_address_house_no', sa.String(length=50), nullable=True),
        
        # Contact Information
        sa.Column('device_branch_contacts_phone_no', sa.String(length=50), nullable=True),
        sa.Column('device_branch_contacts_email', sa.String(length=255), nullable=True),
        
        # Timestamps
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        
        sa.ForeignKeyConstraint(['device_id'], ['device_info.device_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_configuration')
    # ### end Alembic commands ### 