"""Add fiscal_day_no to fiscal_day

Revision ID: edd7f639fd7b
Revises: 
Create Date: 2025-07-24 08:41:22.735322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd7f639fd7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiscal_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fiscal_day_no', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiscal_day', schema=None) as batch_op:
        batch_op.drop_column('fiscal_day_no')

    # ### end Alembic commands ###
