"""manual_add_invoice_tables

Revision ID: manual_invoice_001
Revises: aa335d6de24e
Create Date: 2025-08-01 17:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'manual_invoice_001'
down_revision = 'aa335d6de24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create device_config table
    op.create_table('device_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('device_id', sa.String(length=50), nullable=False),
        sa.Column('config', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['device_info.device_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create invoice table
    op.create_table('invoice',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invoice_id', sa.String(length=100), nullable=False),
        sa.Column('device_id', sa.String(length=50), nullable=False),
        sa.Column('receipt_currency', sa.String(length=10), nullable=False),
        sa.Column('money_type', sa.String(length=20), nullable=False),
        sa.Column('receipt_type', sa.String(length=50), nullable=False),
        sa.Column('receipt_total', sa.Float(), nullable=False),
        sa.Column('zimra_receipt_number', sa.String(length=100), nullable=True),
        sa.Column('operation_id', sa.String(length=100), nullable=True),
        sa.Column('qr_code_string', sa.Text(), nullable=True),
        sa.Column('verification_number', sa.String(length=100), nullable=True),
        sa.Column('hash_string', sa.String(length=255), nullable=True),
        sa.Column('is_fiscalized', sa.Boolean(), nullable=True),
        sa.Column('receipt_counter', sa.Integer(), nullable=True),
        sa.Column('receipt_global_no', sa.Integer(), nullable=True),
        sa.Column('fiscal_day_number', sa.String(length=20), nullable=True),
        sa.Column('receipt_notes', sa.Text(), nullable=True),
        sa.Column('tax_payer_name', sa.String(length=255), nullable=True),
        sa.Column('tax_payer_tin', sa.String(length=50), nullable=True),
        sa.Column('vat_number', sa.String(length=50), nullable=True),
        sa.Column('device_branch_name', sa.String(length=255), nullable=True),
        sa.Column('debit_credit_note_invoice_ref', sa.String(length=100), nullable=True),
        sa.Column('debit_credit_note_invoice_ref_date', sa.DateTime(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('invoice_id')
    )
    
    # Create invoice_line_item table
    op.create_table('invoice_line_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('receipt_line_type', sa.String(length=20), nullable=False),
        sa.Column('receipt_line_no', sa.Integer(), nullable=False),
        sa.Column('receipt_line_hs_code', sa.String(length=20), nullable=True),
        sa.Column('receipt_line_name', sa.String(length=255), nullable=False),
        sa.Column('receipt_line_price', sa.Float(), nullable=False),
        sa.Column('receipt_line_quantity', sa.Float(), nullable=False),
        sa.Column('receipt_line_total', sa.Float(), nullable=False),
        sa.Column('tax_code', sa.String(length=10), nullable=False),
        sa.Column('tax_percent', sa.Float(), nullable=False),
        sa.Column('tax_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create device_branch_address table
    op.create_table('device_branch_address',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('house_no', sa.String(length=50), nullable=True),
        sa.Column('province', sa.String(length=100), nullable=True),
        sa.Column('street', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create device_branch_contact table
    op.create_table('device_branch_contact',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('phone_number', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_branch_contact')
    op.drop_table('device_branch_address')
    op.drop_table('invoice_line_item')
    op.drop_table('invoice')
    op.drop_table('device_config')
    # ### end Alembic commands ### 